### ISSUE TITLE
Panels for CPU, Load, and Memory Not Displaying

### ISSUE THREAD

**Issue by michaelmcdonald** [pecastro/grafana-dashboards#2]
I noticed that on my install I'm getting a large amount of metrics from the bind_exporter; however the three panels that comprise the 2nd row (it appears they display information related to CPU, load, and memory) are not populating with anything. Is there another exporter they should be pulling from? Perhaps the metric they're looking for has changed name (I noticed, as an example, that the CPU panel trying to perform a calculation off of `node_cpu_seconds_total`; however I don't see that as a metric whereas I do see `bind_process_cpu_seconds_total` as an available metric)?

Just thought I would drop a line to see if you had any input or suggestions. Thanks for the great dashboard!!

**Comment by pecastro** [comment]
It seems there's a new version of the bind exporter whereas this dashboard was initially targeting version `0.4.0`.
Can you please confirm the version of your exporter?

**Comment by michaelmcdonald** [comment]
Looks like I'm running version 0.5.0:

```
0>bind_exporter --version
bind_exporter, version 0.5.0 (branch: HEAD, revision: 792f7f381f95fbe5fb319b18cedb9ae6f6ad013b)
  build user:       root@711e62b7164b
  build date:       20211123-09:00:54
  go version:       go1.17.3
  platform:         linux/amd64
```

**Comment by pecastro** [comment]
Looking closely at this, the second row metrics are actually not coming from the exporter but from the host where the exporter might be running.
If you want those metrics you just need the target endpoint to match the name of the host where you might have a node_exporter collecting metrics and those panels will be populated.

**Comment by michaelmcdonald** [comment]
Okay, so there _should_ be another exporter running (one focused on the stats for the machine running `bind_exporter`)? I was confused about that for a minute but it makes more sense now. Appreciate the help!
