### ISSUE TITLE
"Query By Duration" should not be stacked.

### ISSUE THREAD

**Issue by qin-nz** [pecastro/grafana-dashboards#4]
The metrics `bind_resolver_query_duration_seconds_bucket` is a histogram type, which should not be stacked.
![image](https://github.com/user-attachments/assets/04e85d33-a8dd-4c21-aa4f-68aea55a243e)

![image](https://github.com/user-attachments/assets/894eb835-9caf-4f9f-a4a4-b6f7e5cab4f3)

**Comment by pecastro** [comment]
Great spot.
